### ISSUE TITLE
网页的标题能否使用md文件的首个#标注呢

### ISSUE THREAD

**Issue by xm3366336** [bclicn/MarkdownWorm#1]
首先感谢你的贡献，我有个小小问题，想咨询一下：
打开md文件，head.html写的是固定的title，能否像读取列表一样，取出首个#标题，来做为head.html的title呢，求指导，非常感谢！

**Comment by bclicn** [comment]
哇，没想到居然有人会提Issue，简直是人生的里程碑……
那个可以的，因为目前head.html和tail.html是静态的，只有body是PHP动态生成的，所以你只需要把head.html里面的内容挪一部分到body这边来动态生成就可以了。比如把head.html的
`<title>something</title>`
`</head>`
挪到`get.php`的`body`生成部分变成
`echo "<title>".$yourTitle."</title></head>";` 就可以了。
因为PHP效率太低，我后面的网站都准备用GoLang重写了，有兴趣的话可以交流，祝顺利！

**Comment by xm3366336** [comment]
谢谢，已搞定。
我是做app的，只是把想md文件放到自己网站上，刚好找到您的项目，给了我很大的帮助，非常感谢！

**Comment by bclicn** [comment]
客气客气，能帮到你我也很高兴
